"""
services/email_service.py — Send alert emails to doctor via Gmail SMTP.
"""
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

GMAIL_USER = os.getenv("GMAIL_USER", "")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")


def send_alert_email(
    to_email: str,
    patient_name: str,
    severity: str,
    message: str,
    glucose: float,
) -> bool:
    """
    Send an alert email to the doctor.
    Returns True on success, False if credentials are missing or send fails.
    """
    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        print("[email_service] GMAIL credentials not set — skipping email.")
        return False

    subject = f"ALERT: {patient_name} glucose {severity.lower()}"

    body = f"""
<html>
<body style="font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px;">
  <div style="max-width: 600px; margin: auto; background: white; border-radius: 8px;
              padding: 24px; border-left: 6px solid {'#dc2626' if severity == 'CRITICAL' else '#f59e0b'};">
    <h2 style="color: {'#dc2626' if severity == 'CRITICAL' else '#d97706'};">
      ⚠️ {severity} Alert — {patient_name}
    </h2>
    <p><strong>Glucose Reading:</strong> {glucose:.1f} mg/dL</p>
    <p><strong>Alert Details:</strong> {message}</p>
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;">
    <p style="color: #6b7280; font-size: 12px;">
      This alert was generated automatically by the Chronic Monitoring System.
      Please review the patient's dashboard for full details.
    </p>
  </div>
</body>
</html>
"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_USER
    msg["To"] = to_email
    msg.attach(MIMEText(body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, to_email, msg.as_string())
        print(f"[email_service] Alert email sent to {to_email}")
        return True
    except Exception as e:
        print(f"[email_service] Failed to send email: {e}")
        return False


def send_weekly_report_email(
    to_email: str,
    patient_name: str,
    doctor_summary: str,
    risk_score: float,
    week_start: str,
) -> bool:
    """Send weekly AI report email to doctor."""
    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        return False

    risk_color = "#16a34a" if risk_score < 33 else "#d97706" if risk_score < 66 else "#dc2626"
    risk_label = "LOW" if risk_score < 33 else "MEDIUM" if risk_score < 66 else "HIGH"
    subject = f"Weekly Report: {patient_name} (Risk: {risk_label}) — Week of {week_start}"

    body = f"""
<html>
<body style="font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px;">
  <div style="max-width: 600px; margin: auto; background: white; border-radius: 8px; padding: 24px;">
    <h2 style="color: #1e3a5f;">📊 Weekly Report — {patient_name}</h2>
    <p><strong>Week of:</strong> {week_start}</p>
    <p><strong>Risk Score:</strong>
      <span style="color: {risk_color}; font-weight: bold;">{risk_score}/100 ({risk_label})</span>
    </p>
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;">
    <h3 style="color: #374151;">Clinical Note</h3>
    <p style="line-height: 1.6;">{doctor_summary}</p>
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;">
    <p style="color: #6b7280; font-size: 12px;">Generated by Chronic Monitoring System · AI-assisted, rule-scored</p>
  </div>
</body>
</html>
"""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_USER
    msg["To"] = to_email
    msg.attach(MIMEText(body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, to_email, msg.as_string())
        return True
    except Exception as e:
        print(f"[email_service] Failed to send weekly report: {e}")
        return False
